[package]
name = "hdds-gen-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.hdds-gen]
path = ".."

[[bin]]
name = "fuzz_idl_parser"
path = "fuzz_targets/fuzz_idl_parser.rs"
test = false
doc = false
bench = false
