[package]
name = "hdds-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.hdds]
path = ".."

[[bin]]
name = "fuzz_rtps_parser"
path = "fuzz_targets/fuzz_rtps_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_cdr_deser"
path = "fuzz_targets/fuzz_cdr_deser.rs"
test = false
doc = false
bench = false
